
### 基于消息的通信
GET {{host}}:{{port}}/test/message

### 基于事件的通信
GET {{host}}:{{port}}/test/event

### 期望超时
GET {{host}}:{{port}}/test/timeout

### catch错误
GET {{host}}:{{port}}/test/catch

### 过滤器 期待错误
GET {{host}}:{{port}}/test/filter

### 熔断器
GET {{host}}:{{port}}/test/breaker
